VCR into Main
SW8-Mobility/Speed-Limit-Floating-Car-Data pull request #6
Opened 2023-03-20 09:38 UTC by anesheim-uni

2023-03-20 10:35 UTC, frejaz requested changes
Add some tests to vcr_calculator

2023-03-20 10:43 UTC, CasperKjaerhus approved these changes
Nice!

Rename lige VCR_Calculator til noget bedre og følg PEP8

2023-03-21 12:17 UTC, frejaz commented on geo_json_metrics/vcr_calculator.py
> +        velocities (list[float]): A list of floats corresponding to the velocities/speeds
Velocity og speed er to forskellige ting, det du mener er speed (fordi enheden er m/s)

2023-03-21 12:25 UTC, frejaz commented on geo_json_metrics/vcr_calculator.py
> +    return list(map(lambda v1, v2: vcr(v1, v2), velocities[:-1], velocities[1:]))
```suggestion
    # list[:-1] all elements except the last one
    # list[1:] all elements except the first one
    return list(map(lambda v1, v2: vcr(v1, v2), velocities[:-1], velocities[1:]))
```

2023-03-21 12:26 UTC, frejaz commented on geo_json_metrics/vcr_calculator.py
> +    print(map_vcr([1, 2, 3, 4]))
```suggestion

```

2023-03-21 12:28 UTC, frejaz commented on tests/vcr_calculator_test.py
> +@pytest.mark.parametrize(
Der er ingen grund til at bruge parametrize hvis der ikke er mere end én test - tilføj flere hvis den skal være der, ellers er det unødigt overhead

2023-03-21 12:32 UTC, frejaz requested changes
smol stuff

2023-03-29 09:54 UTC, closed without merging